### ISSUE TITLE
Librarian's Balance 'Sealed' books are not directional.

### ISSUE THREAD

**Issue by mistrk7** [RamGemes/Tome-Reader#2]
![image](https://github.com/RamGemes/Tome-Reader/assets/66379077/afecb46a-e3dc-4d4e-a496-05162dce9b2e)

**Comment by mistrk7** [comment]
please fix this when you can

**Comment by mistrk7** [comment]
@RamGemes please fix this when you can

**Comment by Ramixin** [comment]
Fixed as of future release 0.0.5
