### ISSUE TITLE
Change XP levels

### ISSUE THREAD

**Issue by Beez3-A** [RamGemes/Tome-Reader#4]
Good Day 

As the Title states, can we change the XP amount for the random enchants >? 

So that it could be say 10 levels ? 

Thanks

**Comment by Ramixin** [comment]
Hello @Beez3-A,
The reason why the current cost is set to 3 levels is due to the Enchantment table already having textures for XP level costs 1-3. I could add a gamerule that lets the player change the cost in between 1 through 3, but no more since there are no textures for 4+

**Comment by Beez3-A** [comment]
Hello @Ramixin 
okay cool 3 levels is good then I see what you mean
Thanks for the cool Mod
